version :"3"
services:

client :
build : ./client
container_name : client_c
ports :
- "3000:3000"
volumes :
- ./client:/app_client
- ./app_client/node_modules
links: -server

server:
build: ./server
container_name : server_c
ports: 
- "9000:9000"
volumes :
- ./server:/app_server
- ./app_server/node_modules



